import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Comfortaa } from "next/font/google";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

const comfortaa = Comfortaa({
    weight: ["300"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Testing ShadCN",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${comfortaa}`}>
                <nav>
                    <h1>My Favorite Vehicles</h1>
                </nav>
                {children}
            </body>
        </html>
    );
}
